//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEpione
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int AppointmentId { get; set; }
        public System.DateTime AppDate { get; set; }
        public int AppRate { get; set; }
        public string VisitReason { get; set; }
        public int DoctorId { get; set; }
        public Nullable<int> Report_ReportId { get; set; }
    }
}
